files:
  - source: >-
      /src/java/fr/paris/lutece/plugins/participatoryideation/resources/participatoryideation_messages.properties
    translation: >-
      /src/java/fr/paris/lutece/plugins/participatoryideation/resources/participatoryideation_messages_%two_letters_code%.properties
